version: '3.8'

services:
  store-api:
    image: localhost:8082/store-api:${API_VERSION:-latest}
    container_name: store-api
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - nexus

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - app-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - app-network
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  nexus-data:
  prometheus-data:
  grafana-data:

networks:
  app-network:
    driver: bridge