name: 'CI/CD: Build, Publish and Deploy App'

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and Publish to Nexus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Nexus Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NEXUS_REGISTRY_URL }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.NEXUS_REGISTRY_URL }}/store-api:${{ github.sha }}

  deploy:
    name: Deploy Full Stack to EC2
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy project files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yaml,prometheus.yml"
          target: "~/app"

      - name: Deploy services on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export API_VERSION=${{ github.sha }}
            cd ~/app
            docker login ${{ secrets.NEXUS_REGISTRY_URL }} -u ${{ secrets.NEXUS_USERNAME }} -p ${{ secrets.NEXUS_PASSWORD }}
            docker-compose pull
            docker-compose up -d --remove-orphans